[package]
name = "mime"
version = "0.5.0"
alya-version = "0.0.18"
entry = "src/lib.alya"
description = "MIME type and media type detection library for Alya"
authors = ["Alya Language Contributors <https://github.com/alya-lang>"]
license = "MIT"
homepage = "https://github.com/alya-lang/alya"
repository = "https://github.com/alya-lang/mime"
keywords = ["alya", "alya-lang", "package", "mime", "media-type", "content-type", "http", "web"]

[dependencies]
